@startmindmap Citrus
* Citrus
** mckenzie-farms.com
*** Mandarin
****:NO Changsha Mandarin
    while very cold hardy
    small seedy fruit;
**** Satsuma:
*****: Kimbrough Satsuma, 10?
    offer 1°F–2°F better cold 
    tolerance than 'Owari
    see [4];
*****: Owari Satsuma, 12
    see [4];
*****: Browns Select Satsuma
    see [4];
***** others
**** Tangerine
***** Ten Degree Tangerine, 12
*** Kumquats
**** Meiwa 
**** Nagami
*** Kumquat hybrids
**** Nippon Orangequat, 10
****:Thomasville Citrangequat, 5
    see [5];
*** Yuzu

left side

**:Mandarin
    "characterized by their thin, 
    easily peelable skin and sweet 
    flavor." [1] ;
*** Clementines (US)
**** slightly tangy
*** Satsuma (Japan)
**** less acidic
****:"Fruit grown in humid subtropical 
    areas commonly mature internally
    and have good eating quality before 
    good peel color develops.";
*** Tangerine (Tangiers)
**** varies
**:Yuzu
    Lemon-like, fragrant.
    Several recipes for
    pies & marmelades;
** Kumquat
***:Hong Kong, or Golden Bean kumquat 
    (Fortunella hindsii). 
    Primitive, ornamental;
***:Marumi, or round kumquat 
    (F. japonica) aka Luowen
    Ancient  Fruit small, round to slightly oval; rind thick, smooth, orange to yellow-orange, with prominent oil 
    glands, intermediate between Nagami and Meiwa in sweetness; pulp can be dry or fairly juicy; one to six seeds
    ;
***:Meiwa, or large round kumquat 
    (F. X crassifolia ). 
    Jindan or Jingan in China, Neiha in Japan. 
    Natural hybrid of Nagami and Marumi. 
    Best kumquat for eating fresh, popular in Asia. 
    Fruit large, slightly oval to round; rind smooth, orange, very thick and sweet; juice scanty; two to five seeds.
    ;
***:Nagami, or oval kumquat 
    (F. margarita) aka Luofu
    Ancient Chinese kumquat type
    The standard commercial kumquat
    Medium size; oval shape; rind thick, smooth, bright orange, sweet; pulp tart, fairly juicy; flavor spicy, intense, 
    sweet-tart; two to five seeds. 
;
***:Nordmann Seedless kumquat 
    (F. margarita) see [3];
*** Kumquat hybrids

****:Calamondin, or calamansi (Philippines)
    Hybrid of kumquat and sour mandarin, ... 
    juice used for souring
;

@endmindmap
[1] https://www.fourwindsgrowers.com/a/blog/clementines-satsumas-and-tangerines
[2] https://www.fourwindsgrowers.com/a/blog/8-great-kumquat-varieties
[3] (Zotero) https://www.latimes.com/style/la-fow-kumquatside25-2009feb25-story.html
[4] https://edis.ifas.ufl.edu/publication/CH116
[5] https://madisoncitrusnursery.com/products/thomasville-citrangequat-trees-for-sale